name: Daily Script Execution

on:
  schedule:
    - cron: '30 17 * * *'  # Runs at 16:44 UTC every day
  workflow_dispatch:  # Enables manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          python main.py 2>&1 | tee output.log

      - name: Display Python script output
        if: always()
        run: |
          echo "Python Script Output:"
          cat output.log

      - name: Upload log as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: output.log
